# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ArtifactsDependencyGraphNode(BaseModel):
    """
    Recursive dependency node (nested components arrays in responses).
    """ # noqa: E501
    component_name: Optional[StrictStr] = None
    component_id: Optional[StrictStr] = None
    package_type: Optional[StrictStr] = None
    version: Optional[StrictStr] = None
    created: Optional[StrictStr] = None
    modified: Optional[StrictStr] = None
    components: Optional[List[ArtifactsDependencyGraphNode]] = None
    __properties: ClassVar[List[str]] = ["component_name", "component_id", "package_type", "version", "created", "modified", "components"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ArtifactsDependencyGraphNode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in components (list)
        _items = []
        if self.components:
            for _item_components in self.components:
                if _item_components:
                    _items.append(_item_components.to_dict())
            _dict['components'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ArtifactsDependencyGraphNode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "component_name": obj.get("component_name"),
            "component_id": obj.get("component_id"),
            "package_type": obj.get("package_type"),
            "version": obj.get("version"),
            "created": obj.get("created"),
            "modified": obj.get("modified"),
            "components": [ArtifactsDependencyGraphNode.from_dict(_item) for _item in obj["components"]] if obj.get("components") is not None else None
        })
        return _obj

# TODO: Rewrite to not use raise_errors
ArtifactsDependencyGraphNode.model_rebuild(raise_errors=False)

