# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DeleteDirectoryTrashPropertyRequest(BaseModel):
    """
    DeleteDirectoryTrashPropertyRequest
    """ # noqa: E501
    batch_size: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=1000, description="Optional parameter. The number of records to retrieve for a single DB query, should be an integer greater than 0.", alias="batchSize")
    pause_between_batches_ms: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=1000, description="Optional parameter. This parameter defines the pause (in milliseconds) between successive DB query executions. Should be an integer greater than 0.", alias="pauseBetweenBatchesMs")
    batches_count: Optional[StrictInt] = Field(default=-1, description="Optional parameter. This parameter limits the maximum number of DB query executions. For example, if batchesCount = 20 and batchSize is 1,000, then a maximum of (20 * 1,000) = 20,000 records can be deleted", alias="batchesCount")
    __properties: ClassVar[List[str]] = ["batchSize", "pauseBetweenBatchesMs", "batchesCount"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeleteDirectoryTrashPropertyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeleteDirectoryTrashPropertyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "batchSize": obj.get("batchSize") if obj.get("batchSize") is not None else 1000,
            "pauseBetweenBatchesMs": obj.get("pauseBetweenBatchesMs") if obj.get("pauseBetweenBatchesMs") is not None else 1000,
            "batchesCount": obj.get("batchesCount") if obj.get("batchesCount") is not None else -1
        })
        return _obj


