# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jfrog_client.models.get_git_repository_branches200_response_branches_inner import GetGitRepositoryBranches200ResponseBranchesInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetGitRepositoryBranches200Response(BaseModel):
    """
    GetGitRepositoryBranches200Response
    """ # noqa: E501
    page: Optional[StrictInt] = None
    limit: Optional[StrictInt] = None
    total_count: Optional[StrictInt] = None
    repository_id: Optional[StrictInt] = None
    repository_url: Optional[StrictStr] = None
    repository_name: Optional[StrictStr] = None
    branches: Optional[List[GetGitRepositoryBranches200ResponseBranchesInner]] = None
    __properties: ClassVar[List[str]] = ["page", "limit", "total_count", "repository_id", "repository_url", "repository_name", "branches"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGitRepositoryBranches200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in branches (list)
        _items = []
        if self.branches:
            for _item_branches in self.branches:
                if _item_branches:
                    _items.append(_item_branches.to_dict())
            _dict['branches'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGitRepositoryBranches200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "page": obj.get("page"),
            "limit": obj.get("limit"),
            "total_count": obj.get("total_count"),
            "repository_id": obj.get("repository_id"),
            "repository_url": obj.get("repository_url"),
            "repository_name": obj.get("repository_name"),
            "branches": [GetGitRepositoryBranches200ResponseBranchesInner.from_dict(_item) for _item in obj["branches"]] if obj.get("branches") is not None else None
        })
        return _obj


