# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetAllRepositoryConfigurations200Response(BaseModel):
    """
    GetAllRepositoryConfigurations200Response
    """ # noqa: E501
    local: Optional[List[Dict[str, Any]]] = Field(default=None, alias="LOCAL")
    remote: Optional[List[Dict[str, Any]]] = Field(default=None, alias="REMOTE")
    virtual: Optional[List[Dict[str, Any]]] = Field(default=None, alias="VIRTUAL")
    federated: Optional[List[Dict[str, Any]]] = Field(default=None, alias="FEDERATED")
    release_bundle: Optional[List[Dict[str, Any]]] = Field(default=None, alias="RELEASE_BUNDLE")
    __properties: ClassVar[List[str]] = ["LOCAL", "REMOTE", "VIRTUAL", "FEDERATED", "RELEASE_BUNDLE"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetAllRepositoryConfigurations200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetAllRepositoryConfigurations200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "LOCAL": obj.get("LOCAL"),
            "REMOTE": obj.get("REMOTE"),
            "VIRTUAL": obj.get("VIRTUAL"),
            "FEDERATED": obj.get("FEDERATED"),
            "RELEASE_BUNDLE": obj.get("RELEASE_BUNDLE")
        })
        return _obj


