# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetFederationStateSummaries200ResponseFederationStates(BaseModel):
    """
    GetFederationStateSummaries200ResponseFederationStates
    """ # noqa: E501
    healthy: Optional[StrictInt] = Field(default=None, alias="HEALTHY")
    not_available: Optional[StrictInt] = Field(default=None, alias="NOT_AVAILABLE")
    delayed: Optional[StrictInt] = Field(default=None, alias="DELAYED")
    pending_fs: Optional[StrictInt] = Field(default=None, alias="PENDING_FS")
    full_sync_running: Optional[StrictInt] = Field(default=None, alias="FULL_SYNC_RUNNING")
    error: Optional[StrictInt] = Field(default=None, alias="ERROR")
    disabled: Optional[StrictInt] = Field(default=None, alias="DISABLED")
    __properties: ClassVar[List[str]] = ["HEALTHY", "NOT_AVAILABLE", "DELAYED", "PENDING_FS", "FULL_SYNC_RUNNING", "ERROR", "DISABLED"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetFederationStateSummaries200ResponseFederationStates from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetFederationStateSummaries200ResponseFederationStates from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "HEALTHY": obj.get("HEALTHY"),
            "NOT_AVAILABLE": obj.get("NOT_AVAILABLE"),
            "DELAYED": obj.get("DELAYED"),
            "PENDING_FS": obj.get("PENDING_FS"),
            "FULL_SYNC_RUNNING": obj.get("FULL_SYNC_RUNNING"),
            "ERROR": obj.get("ERROR"),
            "DISABLED": obj.get("DISABLED")
        })
        return _obj


