# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetDueDiligenceReportContent200ResponseRowsInner(BaseModel):
    """
    GetDueDiligenceReportContent200ResponseRowsInner
    """ # noqa: E501
    license_key: Optional[StrictStr] = None
    license_name: Optional[StrictStr] = None
    component: Optional[StrictStr] = None
    artifact: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    artifact_scan_time: Optional[StrictStr] = None
    unknown: Optional[StrictBool] = None
    unrecognized: Optional[StrictBool] = None
    custom: Optional[StrictBool] = None
    package_type: Optional[StrictStr] = None
    references: Optional[List[StrictStr]] = None
    impact_path: Optional[List[StrictStr]] = None
    project_keys: Optional[List[StrictStr]] = None
    __properties: ClassVar[List[str]] = ["license_key", "license_name", "component", "artifact", "path", "artifact_scan_time", "unknown", "unrecognized", "custom", "package_type", "references", "impact_path", "project_keys"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetDueDiligenceReportContent200ResponseRowsInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetDueDiligenceReportContent200ResponseRowsInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "license_key": obj.get("license_key"),
            "license_name": obj.get("license_name"),
            "component": obj.get("component"),
            "artifact": obj.get("artifact"),
            "path": obj.get("path"),
            "artifact_scan_time": obj.get("artifact_scan_time"),
            "unknown": obj.get("unknown"),
            "unrecognized": obj.get("unrecognized"),
            "custom": obj.get("custom"),
            "package_type": obj.get("package_type"),
            "references": obj.get("references"),
            "impact_path": obj.get("impact_path"),
            "project_keys": obj.get("project_keys")
        })
        return _obj


