# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from jfrog_client.models.hashicorp_vault_agent_auth import HashicorpVaultAgentAuth
from jfrog_client.models.hashicorp_vault_app_role_auth import HashicorpVaultAppRoleAuth
from jfrog_client.models.hashicorp_vault_certificate_auth import HashicorpVaultCertificateAuth
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

HASHICORPVAULTCONFIGAUTH_ONE_OF_SCHEMAS = ["HashicorpVaultAgentAuth", "HashicorpVaultAppRoleAuth", "HashicorpVaultCertificateAuth"]

class HashicorpVaultConfigAuth(BaseModel):
    """
    Authentication method (`AppRole`, `Certificate`, or `Agent`).
    """
    # data type: HashicorpVaultAppRoleAuth
    oneof_schema_1_validator: Optional[HashicorpVaultAppRoleAuth] = None
    # data type: HashicorpVaultCertificateAuth
    oneof_schema_2_validator: Optional[HashicorpVaultCertificateAuth] = None
    # data type: HashicorpVaultAgentAuth
    oneof_schema_3_validator: Optional[HashicorpVaultAgentAuth] = None
    actual_instance: Optional[Union[HashicorpVaultAgentAuth, HashicorpVaultAppRoleAuth, HashicorpVaultCertificateAuth]] = None
    one_of_schemas: Set[str] = { "HashicorpVaultAgentAuth", "HashicorpVaultAppRoleAuth", "HashicorpVaultCertificateAuth" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = HashicorpVaultConfigAuth.model_construct()
        error_messages = []
        match = 0
        # validate data type: HashicorpVaultAppRoleAuth
        if not isinstance(v, HashicorpVaultAppRoleAuth):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HashicorpVaultAppRoleAuth`")
        else:
            match += 1
        # validate data type: HashicorpVaultCertificateAuth
        if not isinstance(v, HashicorpVaultCertificateAuth):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HashicorpVaultCertificateAuth`")
        else:
            match += 1
        # validate data type: HashicorpVaultAgentAuth
        if not isinstance(v, HashicorpVaultAgentAuth):
            error_messages.append(f"Error! Input type `{type(v)}` is not `HashicorpVaultAgentAuth`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in HashicorpVaultConfigAuth with oneOf schemas: HashicorpVaultAgentAuth, HashicorpVaultAppRoleAuth, HashicorpVaultCertificateAuth. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in HashicorpVaultConfigAuth with oneOf schemas: HashicorpVaultAgentAuth, HashicorpVaultAppRoleAuth, HashicorpVaultCertificateAuth. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into HashicorpVaultAppRoleAuth
        try:
            instance.actual_instance = HashicorpVaultAppRoleAuth.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into HashicorpVaultCertificateAuth
        try:
            instance.actual_instance = HashicorpVaultCertificateAuth.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into HashicorpVaultAgentAuth
        try:
            instance.actual_instance = HashicorpVaultAgentAuth.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into HashicorpVaultConfigAuth with oneOf schemas: HashicorpVaultAgentAuth, HashicorpVaultAppRoleAuth, HashicorpVaultCertificateAuth. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into HashicorpVaultConfigAuth with oneOf schemas: HashicorpVaultAgentAuth, HashicorpVaultAppRoleAuth, HashicorpVaultCertificateAuth. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], HashicorpVaultAgentAuth, HashicorpVaultAppRoleAuth, HashicorpVaultCertificateAuth]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


