# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PudTiming(BaseModel):
    """
    PudTiming
    """ # noqa: E501
    started_at_millis: Optional[StrictInt] = Field(default=None, description="The time in milliseconds when the PUD process started", alias="startedAtMillis")
    started_at: Optional[StrictStr] = Field(default=None, description="The time when the PUD process started. Artifactory returns this without a timezone offset (e.g., \"2024-06-09T15:07:01\"), so the format is a local ISO 8601 datetime string rather than strict RFC 3339. ", alias="startedAt")
    duration_millis: Optional[StrictInt] = Field(default=None, description="The duration of the PUD process in milliseconds up until the point when this report was issued", alias="durationMillis")
    duration: Optional[StrictStr] = Field(default=None, description="The duration of the PUD process up until the point when this report was issued")
    last_updated_millis: Optional[StrictInt] = Field(default=None, description="The time in milliseconds at which this report was issued", alias="lastUpdatedMillis")
    last_updated: Optional[StrictStr] = Field(default=None, description="The time at which this report was issued. Artifactory returns this without a timezone offset (e.g., \"2024-06-09T15:07:15\"), so the format is a local ISO 8601 datetime string rather than strict RFC 3339. ", alias="lastUpdated")
    __properties: ClassVar[List[str]] = ["startedAtMillis", "startedAt", "durationMillis", "duration", "lastUpdatedMillis", "lastUpdated"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PudTiming from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PudTiming from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "startedAtMillis": obj.get("startedAtMillis"),
            "startedAt": obj.get("startedAt"),
            "durationMillis": obj.get("durationMillis"),
            "duration": obj.get("duration"),
            "lastUpdatedMillis": obj.get("lastUpdatedMillis"),
            "lastUpdated": obj.get("lastUpdated")
        })
        return _obj


