# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ReplicationRequest(BaseModel):
    """
    Request object for executing immediate replication. All fields are optional for pull replication; url, username, password are needed only for push replication.
    """ # noqa: E501
    url: Optional[StrictStr] = Field(default=None, description="URL of the repository at the remote Artifactory instance. Used only by push replication.")
    username: Optional[StrictStr] = Field(default=None, description="Username at the remote Artifactory instance. Used only by push replication.")
    password: Optional[StrictStr] = Field(default=None, description="Password at the remote Artifactory instance. Used only by push replication.")
    proxy: Optional[StrictStr] = Field(default=None, description="Name of the proxy (if used) at the remote Artifactory instance. Used only by push replication.")
    disable_proxy: Optional[StrictBool] = Field(default=None, description="When true, disables proxy usage for this replication", alias="disableProxy")
    properties: Optional[StrictBool] = Field(default=True, description="When true, properties of replicated artifacts will be synchronized also (default true)")
    delete: Optional[StrictBool] = Field(default=False, description="When true, items that were deleted remotely will also be deleted locally (including properties metadata) (default false)")
    include_path_prefix_pattern: Optional[StrictStr] = Field(default=None, description="Include path prefix pattern for filtering artifacts to replicate", alias="includePathPrefixPattern")
    exclude_path_prefix_pattern: Optional[StrictStr] = Field(default=None, description="Exclude path prefix pattern for filtering artifacts to replicate", alias="excludePathPrefixPattern")
    check_binary_existence_in_filestore: Optional[StrictBool] = Field(default=None, description="When true, enables distributed checksum storage. Requires Enterprise+ license.", alias="checkBinaryExistenceInFilestore")
    __properties: ClassVar[List[str]] = ["url", "username", "password", "proxy", "disableProxy", "properties", "delete", "includePathPrefixPattern", "excludePathPrefixPattern", "checkBinaryExistenceInFilestore"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReplicationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReplicationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "url": obj.get("url"),
            "username": obj.get("username"),
            "password": obj.get("password"),
            "proxy": obj.get("proxy"),
            "disableProxy": obj.get("disableProxy"),
            "properties": obj.get("properties") if obj.get("properties") is not None else True,
            "delete": obj.get("delete") if obj.get("delete") is not None else False,
            "includePathPrefixPattern": obj.get("includePathPrefixPattern"),
            "excludePathPrefixPattern": obj.get("excludePathPrefixPattern"),
            "checkBinaryExistenceInFilestore": obj.get("checkBinaryExistenceInFilestore")
        })
        return _obj


