# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from jfrog_client.models.retrieve_plugin_info200_response_executions_inner import RetrievePluginInfo200ResponseExecutionsInner
from jfrog_client.models.retrieve_plugin_info200_response_staging_inner import RetrievePluginInfo200ResponseStagingInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RetrievePluginInfo200Response(BaseModel):
    """
    RetrievePluginInfo200Response
    """ # noqa: E501
    executions: Optional[List[RetrievePluginInfo200ResponseExecutionsInner]] = None
    staging: Optional[List[RetrievePluginInfo200ResponseStagingInner]] = None
    __properties: ClassVar[List[str]] = ["executions", "staging"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RetrievePluginInfo200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in executions (list)
        _items = []
        if self.executions:
            for _item_executions in self.executions:
                if _item_executions:
                    _items.append(_item_executions.to_dict())
            _dict['executions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in staging (list)
        _items = []
        if self.staging:
            for _item_staging in self.staging:
                if _item_staging:
                    _items.append(_item_staging.to_dict())
            _dict['staging'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RetrievePluginInfo200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "executions": [RetrievePluginInfo200ResponseExecutionsInner.from_dict(_item) for _item in obj["executions"]] if obj.get("executions") is not None else None,
            "staging": [RetrievePluginInfo200ResponseStagingInner.from_dict(_item) for _item in obj["staging"]] if obj.get("staging") is not None else None
        })
        return _obj


