# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jfrog_client.models.search_build_artifacts_request_mappings_inner import SearchBuildArtifactsRequestMappingsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SearchBuildArtifactsRequest(BaseModel):
    """
    SearchBuildArtifactsRequest
    """ # noqa: E501
    build_name: Optional[StrictStr] = Field(default=None, description="The build name for search by", alias="buildName")
    build_number: Optional[StrictStr] = Field(default=None, description="The build number to search by, can be LATEST to search for the latest build number", alias="buildNumber")
    build_status: Optional[StrictStr] = Field(default=None, description="Optionally search by latest build status (e.g \"Released\")", alias="buildStatus")
    repos: Optional[List[StrictStr]] = Field(default=None, description="Optionally refine search for specific repos, omit to search within all repositories")
    mappings: Optional[List[SearchBuildArtifactsRequestMappingsInner]] = Field(default=None, description="Optionally refine the search by providing a list of regexp patterns to search by")
    __properties: ClassVar[List[str]] = ["buildName", "buildNumber", "buildStatus", "repos", "mappings"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchBuildArtifactsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in mappings (list)
        _items = []
        if self.mappings:
            for _item_mappings in self.mappings:
                if _item_mappings:
                    _items.append(_item_mappings.to_dict())
            _dict['mappings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchBuildArtifactsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "buildName": obj.get("buildName"),
            "buildNumber": obj.get("buildNumber"),
            "buildStatus": obj.get("buildStatus"),
            "repos": obj.get("repos"),
            "mappings": [SearchBuildArtifactsRequestMappingsInner.from_dict(_item) for _item in obj["mappings"]] if obj.get("mappings") is not None else None
        })
        return _obj


