# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from jfrog_client.models.watch_api_v2_request_assigned_policies_inner import WatchApiV2RequestAssignedPoliciesInner
from jfrog_client.models.watch_api_v2_request_general_data import WatchApiV2RequestGeneralData
from jfrog_client.models.watch_api_v2_request_project_resources import WatchApiV2RequestProjectResources
from jfrog_client.models.watch_api_v2_request_ticket_generation import WatchApiV2RequestTicketGeneration
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WatchApiV2Request(BaseModel):
    """
    Request body for creating or updating a Watch in Xray.
    """ # noqa: E501
    general_data: WatchApiV2RequestGeneralData
    project_resources: Optional[WatchApiV2RequestProjectResources] = None
    assigned_policies: Optional[List[WatchApiV2RequestAssignedPoliciesInner]] = Field(default=None, description="Policies assigned to the Watch.")
    watch_recipients: Optional[List[StrictStr]] = Field(default=None, description="Email addresses that will receive Watch notifications.")
    create_ticket_enabled: Optional[StrictBool] = Field(default=None, description="Indicates whether Jira ticket creation is enabled for this Watch.")
    ticket_profile: Optional[StrictStr] = Field(default=None, description="Jira profile name for ticket generation.")
    ticket_generation: Optional[WatchApiV2RequestTicketGeneration] = None
    __properties: ClassVar[List[str]] = ["general_data", "project_resources", "assigned_policies", "watch_recipients", "create_ticket_enabled", "ticket_profile", "ticket_generation"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WatchApiV2Request from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of general_data
        if self.general_data:
            _dict['general_data'] = self.general_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of project_resources
        if self.project_resources:
            _dict['project_resources'] = self.project_resources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in assigned_policies (list)
        _items = []
        if self.assigned_policies:
            for _item_assigned_policies in self.assigned_policies:
                if _item_assigned_policies:
                    _items.append(_item_assigned_policies.to_dict())
            _dict['assigned_policies'] = _items
        # override the default output from pydantic by calling `to_dict()` of ticket_generation
        if self.ticket_generation:
            _dict['ticket_generation'] = self.ticket_generation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WatchApiV2Request from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "general_data": WatchApiV2RequestGeneralData.from_dict(obj["general_data"]) if obj.get("general_data") is not None else None,
            "project_resources": WatchApiV2RequestProjectResources.from_dict(obj["project_resources"]) if obj.get("project_resources") is not None else None,
            "assigned_policies": [WatchApiV2RequestAssignedPoliciesInner.from_dict(_item) for _item in obj["assigned_policies"]] if obj.get("assigned_policies") is not None else None,
            "watch_recipients": obj.get("watch_recipients"),
            "create_ticket_enabled": obj.get("create_ticket_enabled"),
            "ticket_profile": obj.get("ticket_profile"),
            "ticket_generation": WatchApiV2RequestTicketGeneration.from_dict(obj["ticket_generation"]) if obj.get("ticket_generation") is not None else None
        })
        return _obj


