# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.get_the_workers_count200_response_index import GetTheWorkersCount200ResponseIndex

class TestGetTheWorkersCount200ResponseIndex(unittest.TestCase):
    """GetTheWorkersCount200ResponseIndex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetTheWorkersCount200ResponseIndex:
        """Test GetTheWorkersCount200ResponseIndex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetTheWorkersCount200ResponseIndex`
        """
        model = GetTheWorkersCount200ResponseIndex()
        if include_optional:
            return GetTheWorkersCount200ResponseIndex(
                new_content = 56,
                existing_content = 56
            )
        else:
            return GetTheWorkersCount200ResponseIndex(
                new_content = 56,
                existing_content = 56,
        )
        """

    def testGetTheWorkersCount200ResponseIndex(self):
        """Test GetTheWorkersCount200ResponseIndex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
