# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.get_projects_for_role200_response_projects_inner import GetProjectsForRole200ResponseProjectsInner

class TestGetProjectsForRole200ResponseProjectsInner(unittest.TestCase):
    """GetProjectsForRole200ResponseProjectsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetProjectsForRole200ResponseProjectsInner:
        """Test GetProjectsForRole200ResponseProjectsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetProjectsForRole200ResponseProjectsInner`
        """
        model = GetProjectsForRole200ResponseProjectsInner()
        if include_optional:
            return GetProjectsForRole200ResponseProjectsInner(
                name = '',
                project_key = ''
            )
        else:
            return GetProjectsForRole200ResponseProjectsInner(
        )
        """

    def testGetProjectsForRole200ResponseProjectsInner(self):
        """Test GetProjectsForRole200ResponseProjectsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
