# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.federation_target import FederationTarget

class TestFederationTarget(unittest.TestCase):
    """FederationTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FederationTarget:
        """Test FederationTarget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FederationTarget`
        """
        model = FederationTarget()
        if include_optional:
            return FederationTarget(
                name = '',
                url = '',
                entities = [
                    'users'
                    ],
                permission_filters = jfrog_client.models.pattern_filter.PatternFilter(
                    include_patterns = [
                        ''
                        ], 
                    exclude_patterns = [
                        ''
                        ], ),
                group_filters = jfrog_client.models.pattern_filter.PatternFilter(
                    include_patterns = [
                        ''
                        ], 
                    exclude_patterns = [
                        ''
                        ], ),
                active = True
            )
        else:
            return FederationTarget(
        )
        """

    def testFederationTarget(self):
        """Test FederationTarget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
