# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.api.import_api import ImportApi


class TestImportApi(unittest.TestCase):
    """ImportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImportApi()

    def tearDown(self) -> None:
        pass

    def test_full_system_import(self) -> None:
        """Test case for full_system_import

        Full System Import
        """
        pass

    def test_get_import_system_settings_example(self) -> None:
        """Test case for get_import_system_settings_example

        Import System Settings Example
        """
        pass

    def test_import_repository_content(self) -> None:
        """Test case for import_repository_content

        Import Repository Content
        """
        pass


if __name__ == '__main__':
    unittest.main()
