# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.artifact_summary200_response_artifacts_inner_issues_inner import ArtifactSummary200ResponseArtifactsInnerIssuesInner

class TestArtifactSummary200ResponseArtifactsInnerIssuesInner(unittest.TestCase):
    """ArtifactSummary200ResponseArtifactsInnerIssuesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArtifactSummary200ResponseArtifactsInnerIssuesInner:
        """Test ArtifactSummary200ResponseArtifactsInnerIssuesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArtifactSummary200ResponseArtifactsInnerIssuesInner`
        """
        model = ArtifactSummary200ResponseArtifactsInnerIssuesInner()
        if include_optional:
            return ArtifactSummary200ResponseArtifactsInnerIssuesInner(
                issue_id = '',
                summary = '',
                description = '',
                issue_type = '',
                severity = '',
                provider = '',
                cves = [
                    jfrog_client.models.artifact_summary_200_response_artifacts_inner_issues_inner_cves_inner.artifact_summary_200_response_artifacts_inner_issues_inner_cves_inner(
                        cve = '', 
                        cwe = [
                            ''
                            ], 
                        cvss_v2 = '', 
                        cvss_v3 = '', )
                    ],
                created = '',
                impact_path = [
                    ''
                    ],
                extended_information = jfrog_client.models.artifact_summary_200_response_artifacts_inner_issues_inner_extended_information.artifact_summary_200_response_artifacts_inner_issues_inner_extended_information(
                    short_description = '', 
                    full_description = '', 
                    jfrog_research_severity = '', 
                    jfrog_research_severity_reasons = [
                        jfrog_client.models.artifact_summary_200_response_artifacts_inner_issues_inner_extended_information_jfrog_research_severity_reasons_inner.artifact_summary_200_response_artifacts_inner_issues_inner_extended_information_jfrog_research_severity_reasons_inner(
                            name = '', 
                            description = '', 
                            is_positive = True, )
                        ], 
                    remediation = '', ),
                component_physical_paths = [
                    ''
                    ]
            )
        else:
            return ArtifactSummary200ResponseArtifactsInnerIssuesInner(
        )
        """

    def testArtifactSummary200ResponseArtifactsInnerIssuesInner(self):
        """Test ArtifactSummary200ResponseArtifactsInnerIssuesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
