# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.error_response5 import ErrorResponse5

class TestErrorResponse5(unittest.TestCase):
    """ErrorResponse5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorResponse5:
        """Test ErrorResponse5
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponse5`
        """
        model = ErrorResponse5()
        if include_optional:
            return ErrorResponse5(
                errors = [
                    jfrog_client.models.delete_certificate_200_response.deleteCertificate_200_response(
                        status = 56, 
                        message = '', )
                    ]
            )
        else:
            return ErrorResponse5(
        )
        """

    def testErrorResponse5(self):
        """Test ErrorResponse5"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
