# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.group_details import GroupDetails

class TestGroupDetails(unittest.TestCase):
    """GroupDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GroupDetails:
        """Test GroupDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GroupDetails`
        """
        model = GroupDetails()
        if include_optional:
            return GroupDetails(
                name = '',
                description = '',
                auto_join = True,
                admin_privileges = True,
                realm = '',
                realm_attributes = '',
                external_id = '',
                members = [
                    ''
                    ],
                reports_manager = True,
                watch_manager = True,
                policy_manager = True,
                policy_viewer = True,
                manage_resources = True,
                manage_webhook = True
            )
        else:
            return GroupDetails(
        )
        """

    def testGroupDetails(self):
        """Test GroupDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
