# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.get_license_info200_response import GetLicenseInfo200Response

class TestGetLicenseInfo200Response(unittest.TestCase):
    """GetLicenseInfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLicenseInfo200Response:
        """Test GetLicenseInfo200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLicenseInfo200Response`
        """
        model = GetLicenseInfo200Response()
        if include_optional:
            return GetLicenseInfo200Response(
                type = '',
                valid_through = '',
                licensed_to = ''
            )
        else:
            return GetLicenseInfo200Response(
        )
        """

    def testGetLicenseInfo200Response(self):
        """Test GetLicenseInfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
