# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.api.search_v2_api import SearchV2Api


class TestSearchV2Api(unittest.TestCase):
    """SearchV2Api unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchV2Api()

    def tearDown(self) -> None:
        pass

    def test_search_resources_by_vulnerability_and_package(self) -> None:
        """Test case for search_resources_by_vulnerability_and_package

        Search Resources by Vulnerability and Package
        """
        pass


if __name__ == '__main__':
    unittest.main()
