# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.artifact_scan_status200_response_details_exposures_categories import ArtifactScanStatus200ResponseDetailsExposuresCategories

class TestArtifactScanStatus200ResponseDetailsExposuresCategories(unittest.TestCase):
    """ArtifactScanStatus200ResponseDetailsExposuresCategories unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ArtifactScanStatus200ResponseDetailsExposuresCategories:
        """Test ArtifactScanStatus200ResponseDetailsExposuresCategories
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ArtifactScanStatus200ResponseDetailsExposuresCategories`
        """
        model = ArtifactScanStatus200ResponseDetailsExposuresCategories()
        if include_optional:
            return ArtifactScanStatus200ResponseDetailsExposuresCategories(
                iac = jfrog_client.models.artifact_scan_status_200_response_details_sca.artifact_scan_status_200_response_details_sca(
                    status = '', 
                    time = '', ),
                secrets = jfrog_client.models.artifact_scan_status_200_response_details_sca.artifact_scan_status_200_response_details_sca(
                    status = '', 
                    time = '', ),
                services = jfrog_client.models.artifact_scan_status_200_response_details_sca.artifact_scan_status_200_response_details_sca(
                    status = '', 
                    time = '', ),
                applications = jfrog_client.models.artifact_scan_status_200_response_details_sca.artifact_scan_status_200_response_details_sca(
                    status = '', 
                    time = '', )
            )
        else:
            return ArtifactScanStatus200ResponseDetailsExposuresCategories(
        )
        """

    def testArtifactScanStatus200ResponseDetailsExposuresCategories(self):
        """Test ArtifactScanStatus200ResponseDetailsExposuresCategories"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
