# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.force_reindex200_response_failed_send_to_reindex import ForceReindex200ResponseFailedSendToReindex

class TestForceReindex200ResponseFailedSendToReindex(unittest.TestCase):
    """ForceReindex200ResponseFailedSendToReindex unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForceReindex200ResponseFailedSendToReindex:
        """Test ForceReindex200ResponseFailedSendToReindex
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForceReindex200ResponseFailedSendToReindex`
        """
        model = ForceReindex200ResponseFailedSendToReindex()
        if include_optional:
            return ForceReindex200ResponseFailedSendToReindex(
                artifacts = [
                    jfrog_client.models.force_reindex_200_response_failed_send_to_reindex_artifacts_inner.force_reindex_200_response_failed_send_to_reindex_artifacts_inner(
                        repository = '', 
                        path = '', 
                        sha256 = '', 
                        error = '', )
                    ],
                builds = [
                    jfrog_client.models.force_reindex_200_response_failed_send_to_reindex_builds_inner.force_reindex_200_response_failed_send_to_reindex_builds_inner(
                        name = '', 
                        number = '', 
                        build_repo = '', 
                        error = '', )
                    ]
            )
        else:
            return ForceReindex200ResponseFailedSendToReindex(
        )
        """

    def testForceReindex200ResponseFailedSendToReindex(self):
        """Test ForceReindex200ResponseFailedSendToReindex"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
