# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.api.members_api import MembersApi


class TestMembersApi(unittest.TestCase):
    """MembersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MembersApi()

    def tearDown(self) -> None:
        pass

    def test_add_or_update_project_user(self) -> None:
        """Test case for add_or_update_project_user

        Add or Update User in Project
        """
        pass

    def test_delete_project_group(self) -> None:
        """Test case for delete_project_group

        Delete Existing Project's Group
        """
        pass

    def test_delete_project_user(self) -> None:
        """Test case for delete_project_user

        Delete Existing Project's User
        """
        pass

    def test_get_project_group(self) -> None:
        """Test case for get_project_group

        Get Projects Group
        """
        pass

    def test_get_project_groups(self) -> None:
        """Test case for get_project_groups

        Get Projects Groups
        """
        pass

    def test_get_project_user(self) -> None:
        """Test case for get_project_user

        Get Project User
        """
        pass

    def test_get_project_users(self) -> None:
        """Test case for get_project_users

        Get Project Users
        """
        pass

    def test_update_project_group(self) -> None:
        """Test case for update_project_group

        Update Group in Project
        """
        pass


if __name__ == '__main__':
    unittest.main()
