# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.policy_api_v2_response import PolicyApiV2Response

class TestPolicyApiV2Response(unittest.TestCase):
    """PolicyApiV2Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyApiV2Response:
        """Test PolicyApiV2Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyApiV2Response`
        """
        model = PolicyApiV2Response()
        if include_optional:
            return PolicyApiV2Response(
                name = '',
                type = 'security',
                description = '',
                author = '',
                rules = [
                    jfrog_client.models.policy_api_v2_rule_response.PolicyApiV2RuleResponse(
                        name = '', 
                        priority = 56, 
                        criteria = jfrog_client.models.policy_criteria.PolicyCriteria(
                            min_severity = 'critical', 
                            cvss_range = jfrog_client.models.policy_cvss_range.PolicyCvssRange(
                                from = '', 
                                to = '', ), 
                            vulnerability_ids = [
                                ''
                                ], 
                            fix_version_dependant = True, 
                            applicable_cves_only = True, 
                            malicious_package = True, 
                            exposures = jfrog_client.models.policy_exposures.PolicyExposures(
                                min_severity = 'critical', 
                                applications = True, 
                                iac = True, 
                                malicious_code = True, 
                                secrets = True, 
                                services = True, ), 
                            package_name = '', 
                            package_type = 'maven', 
                            package_versions = [
                                ''
                                ], 
                            allow_licenses = [
                                ''
                                ], 
                            allowed_licenses = [
                                ''
                                ], 
                            allow_unknown = True, 
                            banned_licenses = [
                                ''
                                ], 
                            multi_license_permissive = True, 
                            op_risk_min_risk = 'high', 
                            op_risk_custom = jfrog_client.models.policy_op_risk_custom.PolicyOpRiskCustom(
                                op_risk_min_risk = 'high', 
                                use_and_condition = True, 
                                is_eol = True, 
                                commits_less_than = 10, 
                                newer_versions_greater_than = 1, 
                                committers_less_than = 1, 
                                release_date_greater_than_months = 6, 
                                release_cadence_per_year_less_than = 1, 
                                risk = 'high', ), ), 
                        actions = jfrog_client.models.policy_actions_v2_response.PolicyActionsV2Response(
                            mails = [
                                ''
                                ], 
                            webhooks = [
                                ''
                                ], 
                            fail_build = True, 
                            build_failure_grace_period_in_days = 56, 
                            block_download = jfrog_client.models.policy_block_download.PolicyBlockDownload(
                                active = True, 
                                unscanned = True, 
                                grace_period_days = 56, ), 
                            block_release_bundle_distribution = True, 
                            block_release_bundle_promotion = True, 
                            custom_severity = 'critical', 
                            notify_watch_recipients = True, 
                            notify_deployer = True, 
                            create_ticket_enabled = True, ), )
                    ],
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                watches = [
                    ''
                    ],
                project_key = ''
            )
        else:
            return PolicyApiV2Response(
        )
        """

    def testPolicyApiV2Response(self):
        """Test PolicyApiV2Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
