# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.api.garbage_collection_api import GarbageCollectionApi


class TestGarbageCollectionApi(unittest.TestCase):
    """GarbageCollectionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GarbageCollectionApi()

    def tearDown(self) -> None:
        pass

    def test_run_garbage_collection(self) -> None:
        """Test case for run_garbage_collection

        Run Garbage Collection
        """
        pass


if __name__ == '__main__':
    unittest.main()
