# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.permission_list_response import PermissionListResponse

class TestPermissionListResponse(unittest.TestCase):
    """PermissionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermissionListResponse:
        """Test PermissionListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermissionListResponse`
        """
        model = PermissionListResponse()
        if include_optional:
            return PermissionListResponse(
                permissions = [
                    jfrog_client.models.permission_list_response_permissions_inner.PermissionListResponse_permissions_inner(
                        name = '', 
                        uri = '', )
                    ],
                cursor = ''
            )
        else:
            return PermissionListResponse(
        )
        """

    def testPermissionListResponse(self):
        """Test PermissionListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
