# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.api.vcs_api import VCSApi


class TestVCSApi(unittest.TestCase):
    """VCSApi unit test stubs"""

    def setUp(self) -> None:
        self.api = VCSApi()

    def tearDown(self) -> None:
        pass

    def test_download_file_in_vcs_branch_in_subgroup_repository(self) -> None:
        """Test case for download_file_in_vcs_branch_in_subgroup_repository

        Download a File in a VCS Branch in a Subgroup Repository
        """
        pass

    def test_download_file_in_vcs_tag_in_subgroup_repository(self) -> None:
        """Test case for download_file_in_vcs_tag_in_subgroup_repository

        Download a File in a VCS Tag in a Subgroup Repository
        """
        pass

    def test_download_file_within_vcs_branch(self) -> None:
        """Test case for download_file_within_vcs_branch

        Download File within a VCS Branch
        """
        pass

    def test_download_file_within_vcs_branch_alternative(self) -> None:
        """Test case for download_file_within_vcs_branch_alternative

        Download File within a VCS Branch (Alternative Format)
        """
        pass

    def test_download_file_within_vcs_tag(self) -> None:
        """Test case for download_file_within_vcs_tag

        Download File within a VCS Tag
        """
        pass

    def test_download_file_within_vcs_tag_alternative(self) -> None:
        """Test case for download_file_within_vcs_tag_alternative

        Download File within a VCS Tag (Alternative Format)
        """
        pass

    def test_download_vcs_branch(self) -> None:
        """Test case for download_vcs_branch

        Download a VCS Branch
        """
        pass

    def test_download_vcs_branch_alternative(self) -> None:
        """Test case for download_vcs_branch_alternative

        Download a VCS Branch (Alternative Format)
        """
        pass

    def test_download_vcs_branch_from_subgroup_repository(self) -> None:
        """Test case for download_vcs_branch_from_subgroup_repository

        Download a VCS Branch from a Subgroup Repository
        """
        pass

    def test_download_vcs_commit(self) -> None:
        """Test case for download_vcs_commit

        Download a VCS Commit
        """
        pass

    def test_download_vcs_release(self) -> None:
        """Test case for download_vcs_release

        Download a VCS Release
        """
        pass

    def test_download_vcs_tag(self) -> None:
        """Test case for download_vcs_tag

        Download a VCS Tag
        """
        pass

    def test_download_vcs_tag_alternative(self) -> None:
        """Test case for download_vcs_tag_alternative

        Download a VCS Tag (Alternative Format)
        """
        pass

    def test_download_vcs_tag_from_subgroup_repository(self) -> None:
        """Test case for download_vcs_tag_from_subgroup_repository

        Download a VCS Tag from a Subgroup Repository
        """
        pass

    def test_get_vcs_branches(self) -> None:
        """Test case for get_vcs_branches

        Get VCS Branches
        """
        pass

    def test_get_vcs_refs(self) -> None:
        """Test case for get_vcs_refs

        Get VCS Refs
        """
        pass

    def test_get_vcs_tags(self) -> None:
        """Test case for get_vcs_tags

        Get VCS Tags
        """
        pass


if __name__ == '__main__':
    unittest.main()
