# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.build_summary_artifacts_v2_openapi200_response_issues_inner_cves_inner import BuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner

class TestBuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner(unittest.TestCase):
    """BuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner:
        """Test BuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner`
        """
        model = BuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner()
        if include_optional:
            return BuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner(
                cve = '',
                cvss_v2 = '',
                cvss_v3 = ''
            )
        else:
            return BuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner(
        )
        """

    def testBuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner(self):
        """Test BuildSummaryArtifactsV2Openapi200ResponseIssuesInnerCvesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
