# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.get_cve_search_report_details_by_id_request import GetCveSearchReportDetailsByIdRequest

class TestGetCveSearchReportDetailsByIdRequest(unittest.TestCase):
    """GetCveSearchReportDetailsByIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCveSearchReportDetailsByIdRequest:
        """Test GetCveSearchReportDetailsByIdRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCveSearchReportDetailsByIdRequest`
        """
        model = GetCveSearchReportDetailsByIdRequest()
        if include_optional:
            return GetCveSearchReportDetailsByIdRequest(
                filters = jfrog_client.models.get_cve_search_report_details_by_id_request_filters.get_cve_search_report_details_by_id_request_filters(
                    impacted_artifact = '', 
                    scan_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    vulnerable_component = '', )
            )
        else:
            return GetCveSearchReportDetailsByIdRequest(
        )
        """

    def testGetCveSearchReportDetailsByIdRequest(self):
        """Test GetCveSearchReportDetailsByIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
