# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.permission_details_resources import PermissionDetailsResources

class TestPermissionDetailsResources(unittest.TestCase):
    """PermissionDetailsResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PermissionDetailsResources:
        """Test PermissionDetailsResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PermissionDetailsResources`
        """
        model = PermissionDetailsResources()
        if include_optional:
            return PermissionDetailsResources(
                artifact = jfrog_client.models.permission_resource.PermissionResource(
                    actions = jfrog_client.models.actions.Actions(
                        users = {
                            'key' : [
                                ''
                                ]
                            }, 
                        groups = {
                            'key' : [
                                ''
                                ]
                            }, ), 
                    targets = {
                        'key' : jfrog_client.models.patterns.Patterns(
                            include_patterns = [
                                ''
                                ], 
                            exclude_patterns = [
                                ''
                                ], )
                        }, ),
                build = jfrog_client.models.permission_resource.PermissionResource(
                    actions = jfrog_client.models.actions.Actions(
                        users = {
                            'key' : [
                                ''
                                ]
                            }, 
                        groups = {
                            'key' : [
                                ''
                                ]
                            }, ), 
                    targets = {
                        'key' : jfrog_client.models.patterns.Patterns(
                            include_patterns = [
                                ''
                                ], 
                            exclude_patterns = [
                                ''
                                ], )
                        }, ),
                release_bundle = jfrog_client.models.permission_resource.PermissionResource(
                    actions = jfrog_client.models.actions.Actions(
                        users = {
                            'key' : [
                                ''
                                ]
                            }, 
                        groups = {
                            'key' : [
                                ''
                                ]
                            }, ), 
                    targets = {
                        'key' : jfrog_client.models.patterns.Patterns(
                            include_patterns = [
                                ''
                                ], 
                            exclude_patterns = [
                                ''
                                ], )
                        }, )
            )
        else:
            return PermissionDetailsResources(
        )
        """

    def testPermissionDetailsResources(self):
        """Test PermissionDetailsResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
