# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.jpd_create import JpdCreate

class TestJpdCreate(unittest.TestCase):
    """JpdCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JpdCreate:
        """Test JpdCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JpdCreate`
        """
        model = JpdCreate()
        if include_optional:
            return JpdCreate(
                name = '',
                url = '',
                location = jfrog_client.models.jpd_create_location.JpdCreate_location(
                    city_name = '', 
                    country_code = '', 
                    latitude = 1.337, 
                    longitude = 1.337, ),
                token = '',
                username = '',
                password = '',
                tags = [
                    ''
                    ]
            )
        else:
            return JpdCreate(
                name = '',
                url = '',
                location = jfrog_client.models.jpd_create_location.JpdCreate_location(
                    city_name = '', 
                    country_code = '', 
                    latitude = 1.337, 
                    longitude = 1.337, ),
        )
        """

    def testJpdCreate(self):
        """Test JpdCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
