# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.search_latest_version_by_properties200_response import SearchLatestVersionByProperties200Response

class TestSearchLatestVersionByProperties200Response(unittest.TestCase):
    """SearchLatestVersionByProperties200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchLatestVersionByProperties200Response:
        """Test SearchLatestVersionByProperties200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchLatestVersionByProperties200Response`
        """
        model = SearchLatestVersionByProperties200Response()
        if include_optional:
            return SearchLatestVersionByProperties200Response(
                version = '',
                artifacts = [
                    jfrog_client.models.search_latest_version_by_properties_200_response_artifacts_inner.searchLatestVersionByProperties_200_response_artifacts_inner(
                        uri = '', )
                    ]
            )
        else:
            return SearchLatestVersionByProperties200Response(
        )
        """

    def testSearchLatestVersionByProperties200Response(self):
        """Test SearchLatestVersionByProperties200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
