# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.reports_cve_search_report_request import ReportsCveSearchReportRequest

class TestReportsCveSearchReportRequest(unittest.TestCase):
    """ReportsCveSearchReportRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportsCveSearchReportRequest:
        """Test ReportsCveSearchReportRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportsCveSearchReportRequest`
        """
        model = ReportsCveSearchReportRequest()
        if include_optional:
            return ReportsCveSearchReportRequest(
                cve = '',
                name = '',
                resources = jfrog_client.models.reports_resources_block.ReportsResourcesBlock(
                    repositories = [
                        jfrog_client.models.reports_repository_entry.ReportsRepositoryEntry(
                            name = '', 
                            include_path_patterns = [
                                ''
                                ], 
                            exclude_path_patterns = [
                                ''
                                ], )
                        ], 
                    builds = jfrog_client.models.reports_builds_scope.ReportsBuildsScope(
                        names = [
                            ''
                            ], 
                        include_patterns = [
                            ''
                            ], 
                        exclude_patterns = [
                            ''
                            ], 
                        number_of_latest_versions = 56, ), 
                    release_bundles = jfrog_client.models.reports_named_scope_with_patterns.ReportsNamedScopeWithPatterns(
                        number_of_latest_versions = 56, ), 
                    release_bundles_v2 = jfrog_client.models.reports_builds_scope.ReportsBuildsScope(
                        number_of_latest_versions = 56, ), 
                    projects = jfrog_client.models.reports_projects_scope.ReportsProjectsScope(
                        keys = [
                            ''
                            ], 
                        include_key_patterns = [
                            ''
                            ], 
                        exclude_key_patterns = [
                            ''
                            ], 
                        number_of_latest_versions = 56, ), ),
                filters = jfrog_client.models.reports_cve_search_report_request_filters.ReportsCveSearchReportRequest_filters(
                    vulnerable_component = '', 
                    impacted_artifact = '', 
                    scan_date = jfrog_client.models.reports_date_range.ReportsDateRange(
                        start = '', 
                        end = '', ), 
                    runtime_filter = True, 
                    ca_filter = True, )
            )
        else:
            return ReportsCveSearchReportRequest(
                cve = '',
                resources = jfrog_client.models.reports_resources_block.ReportsResourcesBlock(
                    repositories = [
                        jfrog_client.models.reports_repository_entry.ReportsRepositoryEntry(
                            name = '', 
                            include_path_patterns = [
                                ''
                                ], 
                            exclude_path_patterns = [
                                ''
                                ], )
                        ], 
                    builds = jfrog_client.models.reports_builds_scope.ReportsBuildsScope(
                        names = [
                            ''
                            ], 
                        include_patterns = [
                            ''
                            ], 
                        exclude_patterns = [
                            ''
                            ], 
                        number_of_latest_versions = 56, ), 
                    release_bundles = jfrog_client.models.reports_named_scope_with_patterns.ReportsNamedScopeWithPatterns(
                        number_of_latest_versions = 56, ), 
                    release_bundles_v2 = jfrog_client.models.reports_builds_scope.ReportsBuildsScope(
                        number_of_latest_versions = 56, ), 
                    projects = jfrog_client.models.reports_projects_scope.ReportsProjectsScope(
                        keys = [
                            ''
                            ], 
                        include_key_patterns = [
                            ''
                            ], 
                        exclude_key_patterns = [
                            ''
                            ], 
                        number_of_latest_versions = 56, ), ),
        )
        """

    def testReportsCveSearchReportRequest(self):
        """Test ReportsCveSearchReportRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
