# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.retrieve_plugin_info_of_certain_type200_response import RetrievePluginInfoOfCertainType200Response

class TestRetrievePluginInfoOfCertainType200Response(unittest.TestCase):
    """RetrievePluginInfoOfCertainType200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RetrievePluginInfoOfCertainType200Response:
        """Test RetrievePluginInfoOfCertainType200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RetrievePluginInfoOfCertainType200Response`
        """
        model = RetrievePluginInfoOfCertainType200Response()
        if include_optional:
            return RetrievePluginInfoOfCertainType200Response(
                executions = [
                    None
                    ],
                staging = [
                    None
                    ]
            )
        else:
            return RetrievePluginInfoOfCertainType200Response(
        )
        """

    def testRetrievePluginInfoOfCertainType200Response(self):
        """Test RetrievePluginInfoOfCertainType200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
