# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.ignore_rule_filters_exposures import IgnoreRuleFiltersExposures

class TestIgnoreRuleFiltersExposures(unittest.TestCase):
    """IgnoreRuleFiltersExposures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IgnoreRuleFiltersExposures:
        """Test IgnoreRuleFiltersExposures
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IgnoreRuleFiltersExposures`
        """
        model = IgnoreRuleFiltersExposures()
        if include_optional:
            return IgnoreRuleFiltersExposures(
                scanners = [
                    ''
                    ],
                categories = [
                    ''
                    ],
                file_path = [
                    ''
                    ],
                file_path_pattern = [
                    ''
                    ],
                fingerprints = [
                    ''
                    ]
            )
        else:
            return IgnoreRuleFiltersExposures(
        )
        """

    def testIgnoreRuleFiltersExposures(self):
        """Test IgnoreRuleFiltersExposures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
