# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.api.service_trust_api import ServiceTrustApi


class TestServiceTrustApi(unittest.TestCase):
    """ServiceTrustApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceTrustApi()

    def tearDown(self) -> None:
        pass

    def test_exchange_pairing_token(self) -> None:
        """Test case for exchange_pairing_token

        Exchange Pairing Token
        """
        pass

    def test_generate_pairing_token(self) -> None:
        """Test case for generate_pairing_token

        Generate Pairing Token
        """
        pass

    def test_unregister_pairing_token(self) -> None:
        """Test case for unregister_pairing_token

        Unregister Pairing Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
