# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.get_build_dependency_graph200_response_build import GetBuildDependencyGraph200ResponseBuild

class TestGetBuildDependencyGraph200ResponseBuild(unittest.TestCase):
    """GetBuildDependencyGraph200ResponseBuild unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetBuildDependencyGraph200ResponseBuild:
        """Test GetBuildDependencyGraph200ResponseBuild
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetBuildDependencyGraph200ResponseBuild`
        """
        model = GetBuildDependencyGraph200ResponseBuild()
        if include_optional:
            return GetBuildDependencyGraph200ResponseBuild(
                name = '',
                path = '',
                pkg_type = '',
                sha256 = '',
                component_id = ''
            )
        else:
            return GetBuildDependencyGraph200ResponseBuild(
                name = '',
                path = '',
                pkg_type = '',
                sha256 = '',
                component_id = '',
        )
        """

    def testGetBuildDependencyGraph200ResponseBuild(self):
        """Test GetBuildDependencyGraph200ResponseBuild"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
