# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.get_reverse_proxy_configuration200_response import GetReverseProxyConfiguration200Response

class TestGetReverseProxyConfiguration200Response(unittest.TestCase):
    """GetReverseProxyConfiguration200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetReverseProxyConfiguration200Response:
        """Test GetReverseProxyConfiguration200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetReverseProxyConfiguration200Response`
        """
        model = GetReverseProxyConfiguration200Response()
        if include_optional:
            return GetReverseProxyConfiguration200Response(
                key = '',
                web_server_type = '',
                artifactory_app_context = '',
                public_app_context = '',
                server_name = '',
                server_name_expression = '',
                artifactory_server_name = '',
                artifactory_port = 56,
                ssl_certificate = '',
                ssl_key = '',
                docker_reverse_proxy_method = 'SUBDOMAIN',
                use_https = True,
                use_http = True,
                ssl_port = 56,
                http_port = 56
            )
        else:
            return GetReverseProxyConfiguration200Response(
        )
        """

    def testGetReverseProxyConfiguration200Response(self):
        """Test GetReverseProxyConfiguration200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
