# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.user_configuration import UserConfiguration

class TestUserConfiguration(unittest.TestCase):
    """UserConfiguration unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserConfiguration:
        """Test UserConfiguration
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserConfiguration`
        """
        model = UserConfiguration()
        if include_optional:
            return UserConfiguration(
                name = '',
                email = '',
                last_logged_in = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                realm = '',
                admin = True,
                profile_updatable = True,
                internal_password_disabled = True,
                groups = [
                    ''
                    ],
                disable_ui_access = True,
                policy_viewer = True,
                policy_manager = True,
                watch_manager = True,
                reports_manager = True,
                mfa_status = 'NONE',
                status = 'ENABLED'
            )
        else:
            return UserConfiguration(
        )
        """

    def testUserConfiguration(self):
        """Test UserConfiguration"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
