# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.api.custom_issues_v1_api import CustomIssuesV1Api


class TestCustomIssuesV1Api(unittest.TestCase):
    """CustomIssuesV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomIssuesV1Api()

    def tearDown(self) -> None:
        pass

    def test_create_issue_event(self) -> None:
        """Test case for create_issue_event

        Create Issue Event
        """
        pass

    def test_delete_issue_event(self) -> None:
        """Test case for delete_issue_event

        Delete Issue Event
        """
        pass

    def test_update_issue_event(self) -> None:
        """Test case for update_issue_event

        Update Issue Event
        """
        pass


if __name__ == '__main__':
    unittest.main()
