# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.update_repositories_configurations_request import UpdateRepositoriesConfigurationsRequest

class TestUpdateRepositoriesConfigurationsRequest(unittest.TestCase):
    """UpdateRepositoriesConfigurationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateRepositoriesConfigurationsRequest:
        """Test UpdateRepositoriesConfigurationsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateRepositoriesConfigurationsRequest`
        """
        model = UpdateRepositoriesConfigurationsRequest()
        if include_optional:
            return UpdateRepositoriesConfigurationsRequest(
                repo_name = '',
                repo_config = jfrog_client.models.update_repositories_configurations_request_repo_config.update_repositories_configurations_request_repo_config(
                    vuln_contextual_analysis = True, 
                    retention_in_days = 56, 
                    exposures = jfrog_client.models.update_repositories_configurations_request_repo_config_exposures.update_repositories_configurations_request_repo_config_exposures(
                        scanners_category = jfrog_client.models.update_repositories_configurations_request_repo_config_exposures_scanners_category.update_repositories_configurations_request_repo_config_exposures_scanners_category(
                            services_scan = True, 
                            secrets_scan = True, 
                            applications_scan = True, ), ), ),
                repo_paths_config = jfrog_client.models.update_repositories_configurations_request_repo_paths_config.update_repositories_configurations_request_repo_paths_config(
                    patterns = [
                        jfrog_client.models.update_repositories_configurations_request_repo_paths_config_patterns_inner.update_repositories_configurations_request_repo_paths_config_patterns_inner(
                            include = '', 
                            exclude = '', 
                            index_new_artifacts = True, 
                            retention_in_days = 56, )
                        ], 
                    all_other_artifacts = jfrog_client.models.update_repositories_configurations_request_repo_paths_config_all_other_artifacts.update_repositories_configurations_request_repo_paths_config_all_other_artifacts(
                        index_new_artifacts = True, 
                        retention_in_days = 56, ), )
            )
        else:
            return UpdateRepositoriesConfigurationsRequest(
                repo_name = '',
        )
        """

    def testUpdateRepositoriesConfigurationsRequest(self):
        """Test UpdateRepositoriesConfigurationsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
