# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.api.scanning_v1_api import ScanningV1Api


class TestScanningV1Api(unittest.TestCase):
    """ScanningV1Api unit test stubs"""

    def setUp(self) -> None:
        self.api = ScanningV1Api()

    def tearDown(self) -> None:
        pass

    def test_abort_a_running_repository_scan(self) -> None:
        """Test case for abort_a_running_repository_scan

        Cancel Repository Advanced Scan
        """
        pass

    def test_apply_watch_on_existing_content(self) -> None:
        """Test case for apply_watch_on_existing_content

        Apply Watch on Existing Content
        """
        pass

    def test_artifact_scan_status(self) -> None:
        """Test case for artifact_scan_status

        Artifact Scan Status
        """
        pass

    def test_build_scan_status(self) -> None:
        """Test case for build_scan_status

        Build Scan Status
        """
        pass

    def test_cancel_a_running_scan(self) -> None:
        """Test case for cancel_a_running_scan

        Cancel Artifact Exposures Scan
        """
        pass

    def test_delete_on_demand_scan_results(self) -> None:
        """Test case for delete_on_demand_scan_results

        Delete On-Demand Scan Results
        """
        pass

    def test_get_exposure_result_details(self) -> None:
        """Test case for get_exposure_result_details

        Exposures Scanning - Get Results Details
        """
        pass

    def test_get_exposure_result_list(self) -> None:
        """Test case for get_exposure_result_list

        Exposures Scanning - Get Results List
        """
        pass

    def test_get_more_exposure_result_evidence_rows(self) -> None:
        """Test case for get_more_exposure_result_evidence_rows

        Exposures Scanning - Get Rows
        """
        pass

    def test_get_more_exposure_result_evidences(self) -> None:
        """Test case for get_more_exposure_result_evidences

        Exposures Scanning - Get Evidence
        """
        pass

    def test_get_more_exposure_result_findings(self) -> None:
        """Test case for get_more_exposure_result_findings

        Exposures Scanning - Get Findings
        """
        pass

    def test_get_the_status_of_a_running_repository_scan(self) -> None:
        """Test case for get_the_status_of_a_running_repository_scan

        Get Repository Advanced Scan Status
        """
        pass

    def test_release_bundle_scan_status(self) -> None:
        """Test case for release_bundle_scan_status

        Release Bundle Scan Status
        """
        pass

    def test_release_bundle_v2_scan_status(self) -> None:
        """Test case for release_bundle_v2_scan_status

        Release Bundle V2 Scan Status
        """
        pass

    def test_repository_advanced_scans(self) -> None:
        """Test case for repository_advanced_scans

        Repository Advanced Scans
        """
        pass

    def test_scan_artifact(self) -> None:
        """Test case for scan_artifact

        Scan Artifact
        """
        pass

    def test_scan_artifact_for_exposures(self) -> None:
        """Test case for scan_artifact_for_exposures

        Scan Artifact for Exposures
        """
        pass

    def test_scan_build_v1(self) -> None:
        """Test case for scan_build_v1

        Scan Build V1
        """
        pass

    def test_scan_status_of_an_artifact(self) -> None:
        """Test case for scan_status_of_an_artifact

        Get Artifact Exposures Scan Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
