# coding: utf-8

"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jfrog_client.models.watch_api_v2_request_project_resources import WatchApiV2RequestProjectResources

class TestWatchApiV2RequestProjectResources(unittest.TestCase):
    """WatchApiV2RequestProjectResources unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WatchApiV2RequestProjectResources:
        """Test WatchApiV2RequestProjectResources
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WatchApiV2RequestProjectResources`
        """
        model = WatchApiV2RequestProjectResources()
        if include_optional:
            return WatchApiV2RequestProjectResources(
                resources = [
                    jfrog_client.models.watch_api_v2_request_project_resources_resources_inner.WatchApiV2Request_project_resources_resources_inner(
                        type = 'repository', 
                        name = '', 
                        bin_mgr_id = '', 
                        repo_type = 'local', 
                        build_repo = '', 
                        project = '', 
                        filters = [
                            jfrog_client.models.watch_api_v2_request_project_resources_resources_inner_filters_inner.WatchApiV2Request_project_resources_resources_inner_filters_inner(
                                type = 'regex', 
                                value = null, )
                            ], )
                    ],
                global_filters = [
                    jfrog_client.models.watch_api_v2_request_project_resources_global_filters_inner.WatchApiV2Request_project_resources_global_filters_inner(
                        type = '', 
                        value = null, )
                    ]
            )
        else:
            return WatchApiV2RequestProjectResources(
        )
        """

    def testWatchApiV2RequestProjectResources(self):
        """Test WatchApiV2RequestProjectResources"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
