"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictBytes, StrictInt, StrictStr, field_validator
from typing import List, Optional, Tuple, Union
from typing_extensions import Annotated
from jfrog_client.models.build_artifacts_request import BuildArtifactsRequest
from jfrog_client.models.ruby_gem_version import RubyGemVersion

from jfrog_client.api_client import ApiClient, RequestSerialized
from jfrog_client.api_response import ApiResponse
from jfrog_client.rest import RESTResponseType


class ArtifactRetrievalApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def archive_entry_download(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        archive_path: Annotated[str, Field(min_length=1, strict=True, description="Path to the archive file")],
        entry_path: Annotated[str, Field(min_length=1, strict=True, description="Path to the resource within the archive (e.g., META-INF/MANIFEST.MF)")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Archive Entry Download

        Returns an archived resource from the specified archive destination.  The `!` must be between the archive file name and the archive entry path, and will not work without the `/` after the `!`.  Security: Requires a user with 'read' permission (can be anonymous) 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param archive_path: Path to the archive file (required)
        :type archive_path: str
        :param entry_path: Path to the resource within the archive (e.g., META-INF/MANIFEST.MF) (required)
        :type entry_path: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._archive_entry_download_serialize(
            repo_key=repo_key,
            archive_path=archive_path,
            entry_path=entry_path,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def archive_entry_download_with_http_info(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        archive_path: Annotated[str, Field(min_length=1, strict=True, description="Path to the archive file")],
        entry_path: Annotated[str, Field(min_length=1, strict=True, description="Path to the resource within the archive (e.g., META-INF/MANIFEST.MF)")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Archive Entry Download

        Returns an archived resource from the specified archive destination.  The `!` must be between the archive file name and the archive entry path, and will not work without the `/` after the `!`.  Security: Requires a user with 'read' permission (can be anonymous) 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param archive_path: Path to the archive file (required)
        :type archive_path: str
        :param entry_path: Path to the resource within the archive (e.g., META-INF/MANIFEST.MF) (required)
        :type entry_path: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._archive_entry_download_serialize(
            repo_key=repo_key,
            archive_path=archive_path,
            entry_path=entry_path,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def archive_entry_download_without_preload_content(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        archive_path: Annotated[str, Field(min_length=1, strict=True, description="Path to the archive file")],
        entry_path: Annotated[str, Field(min_length=1, strict=True, description="Path to the resource within the archive (e.g., META-INF/MANIFEST.MF)")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Archive Entry Download

        Returns an archived resource from the specified archive destination.  The `!` must be between the archive file name and the archive entry path, and will not work without the `/` after the `!`.  Security: Requires a user with 'read' permission (can be anonymous) 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param archive_path: Path to the archive file (required)
        :type archive_path: str
        :param entry_path: Path to the resource within the archive (e.g., META-INF/MANIFEST.MF) (required)
        :type entry_path: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._archive_entry_download_serialize(
            repo_key=repo_key,
            archive_path=archive_path,
            entry_path=entry_path,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _archive_entry_download_serialize(
        self,
        repo_key,
        archive_path,
        entry_path,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if repo_key is not None:
            _path_params['repoKey'] = repo_key
        if archive_path is not None:
            _path_params['archivePath'] = archive_path
        if entry_path is not None:
            _path_params['entryPath'] = entry_path
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'text/plain', 
                    'application/octet-stream', 
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/artifactory/api/{repoKey}/{archivePath}!/{entryPath}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def artifact_sync_download(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        file_path: Annotated[str, Field(min_length=1, strict=True, description="File path within the repository")],
        content: Annotated[Optional[StrictStr], Field(description="Content mode (none, progress, or omit for full content)")] = None,
        mark: Annotated[Optional[StrictInt], Field(description="Number of bytes to print a new progress mark")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> bytes:
        """Artifact Sync Download

        Downloads an artifact with or without returning the actual content to the client. When tracking the progress marks are printed (by default every 1024 bytes). This is extremely useful if you want to trigger downloads on a remote Artifactory server, for example to force eager cache population of large artifacts, but want to avoid the bandwidth consumption involved in transferring the artifacts to the triggering client.   Notes: Requires Artifactory Pro.  Since: 2.2.2  Security: Requires a privileged user (can be anonymous) 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param file_path: File path within the repository (required)
        :type file_path: str
        :param content: Content mode (none, progress, or omit for full content)
        :type content: str
        :param mark: Number of bytes to print a new progress mark
        :type mark: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._artifact_sync_download_serialize(
            repo_key=repo_key,
            file_path=file_path,
            content=content,
            mark=mark,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '400': "str",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def artifact_sync_download_with_http_info(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        file_path: Annotated[str, Field(min_length=1, strict=True, description="File path within the repository")],
        content: Annotated[Optional[StrictStr], Field(description="Content mode (none, progress, or omit for full content)")] = None,
        mark: Annotated[Optional[StrictInt], Field(description="Number of bytes to print a new progress mark")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[bytes]:
        """Artifact Sync Download

        Downloads an artifact with or without returning the actual content to the client. When tracking the progress marks are printed (by default every 1024 bytes). This is extremely useful if you want to trigger downloads on a remote Artifactory server, for example to force eager cache population of large artifacts, but want to avoid the bandwidth consumption involved in transferring the artifacts to the triggering client.   Notes: Requires Artifactory Pro.  Since: 2.2.2  Security: Requires a privileged user (can be anonymous) 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param file_path: File path within the repository (required)
        :type file_path: str
        :param content: Content mode (none, progress, or omit for full content)
        :type content: str
        :param mark: Number of bytes to print a new progress mark
        :type mark: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._artifact_sync_download_serialize(
            repo_key=repo_key,
            file_path=file_path,
            content=content,
            mark=mark,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '400': "str",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def artifact_sync_download_without_preload_content(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        file_path: Annotated[str, Field(min_length=1, strict=True, description="File path within the repository")],
        content: Annotated[Optional[StrictStr], Field(description="Content mode (none, progress, or omit for full content)")] = None,
        mark: Annotated[Optional[StrictInt], Field(description="Number of bytes to print a new progress mark")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Artifact Sync Download

        Downloads an artifact with or without returning the actual content to the client. When tracking the progress marks are printed (by default every 1024 bytes). This is extremely useful if you want to trigger downloads on a remote Artifactory server, for example to force eager cache population of large artifacts, but want to avoid the bandwidth consumption involved in transferring the artifacts to the triggering client.   Notes: Requires Artifactory Pro.  Since: 2.2.2  Security: Requires a privileged user (can be anonymous) 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param file_path: File path within the repository (required)
        :type file_path: str
        :param content: Content mode (none, progress, or omit for full content)
        :type content: str
        :param mark: Number of bytes to print a new progress mark
        :type mark: int
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._artifact_sync_download_serialize(
            repo_key=repo_key,
            file_path=file_path,
            content=content,
            mark=mark,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '400': "str",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _artifact_sync_download_serialize(
        self,
        repo_key,
        file_path,
        content,
        mark,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if repo_key is not None:
            _path_params['repoKey'] = repo_key
        if file_path is not None:
            _path_params['filePath'] = file_path
        # process the query parameters
        if content is not None:
            
            _query_params.append(('content', content))
            
        if mark is not None:
            
            _query_params.append(('mark', mark))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/octet-stream', 
                    'text/plain', 
                    'text/html', 
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/artifactory/api/download/{repoKey}/{filePath}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_ruby_gem_version_list(
        self,
        repo_name: Annotated[str, Field(min_length=1, strict=True, description="Repository name")],
        gem_name: Annotated[str, Field(min_length=1, strict=True, description="Gem name")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> List[RubyGemVersion]:
        """Get RubyGem Version List

        Returns the list of versions and other metadata associated with a specific Ruby gem.

        :param repo_name: Repository name (required)
        :type repo_name: str
        :param gem_name: Gem name (required)
        :type gem_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_ruby_gem_version_list_serialize(
            repo_name=repo_name,
            gem_name=gem_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[RubyGemVersion]",
            '401': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_ruby_gem_version_list_with_http_info(
        self,
        repo_name: Annotated[str, Field(min_length=1, strict=True, description="Repository name")],
        gem_name: Annotated[str, Field(min_length=1, strict=True, description="Gem name")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[List[RubyGemVersion]]:
        """Get RubyGem Version List

        Returns the list of versions and other metadata associated with a specific Ruby gem.

        :param repo_name: Repository name (required)
        :type repo_name: str
        :param gem_name: Gem name (required)
        :type gem_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_ruby_gem_version_list_serialize(
            repo_name=repo_name,
            gem_name=gem_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[RubyGemVersion]",
            '401': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_ruby_gem_version_list_without_preload_content(
        self,
        repo_name: Annotated[str, Field(min_length=1, strict=True, description="Repository name")],
        gem_name: Annotated[str, Field(min_length=1, strict=True, description="Gem name")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get RubyGem Version List

        Returns the list of versions and other metadata associated with a specific Ruby gem.

        :param repo_name: Repository name (required)
        :type repo_name: str
        :param gem_name: Gem name (required)
        :type gem_name: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_ruby_gem_version_list_serialize(
            repo_name=repo_name,
            gem_name=gem_name,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "List[RubyGemVersion]",
            '401': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_ruby_gem_version_list_serialize(
        self,
        repo_name,
        gem_name,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if repo_name is not None:
            _path_params['repoName'] = repo_name
        if gem_name is not None:
            _path_params['gemName'] = gem_name
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'application/yaml'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/artifactory/api/gems/{repoName}/api/v1/versions/{gemName}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def retrieve_artifact(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        file_path: Annotated[str, Field(min_length=1, strict=True, description="Path to the artifact within the repository. Can include special tokens: SNAPSHOT, [RELEASE], [INTEGRATION] for latest version resolution.")],
        skip_update_stats: Annotated[Optional[StrictBool], Field(description="Skip updating download statistics for this artifact")] = None,
        trace: Annotated[Optional[StrictBool], Field(description="Simulates an artifact retrieval request and returns verbose output about the resolution process. Useful for debugging artifact retrieval issues.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> bytes:
        """Retrieve Artifact

        Returns an artifact from the specified destination.  You can also use properties in deployment and resolution as part of retrieving artifacts.  Special tokens for retrieving latest versions: - **Latest Maven Release/Integration**: Specify SNAPSHOT or [RELEASE] for the version in the requested path to get the latest Maven integration or release artifact. - **Latest Non-Maven Release/Integration**: Specify [INTEGRATION] and [RELEASE] for the version in the requested path (replacing [folderItegRev] and [fileItegRev], as defined by the repository's Repository Layouts) to get the latest integration version or latest release version artifact accordingly based on alphabetical sorting.  Notes: - Integration and release tokens cannot be mixed together. - Only local, cache and virtual repositories will be used for latest version resolution. - To change the retrieve latest behavior to retrieve the latest version based on the created date, add `artifactory.request.searchLatestReleaseByDateCreated=true` to `artifactory.system.properties` and restart Artifactory. - Both [folderItegRev] and [fileItegRev] have to be defined in the repository layout. - Latest version resolution requires Artifactory Pro.  Since: Latest Maven: 2.6.0; Latest non-Maven: 2.6.2 Security: Requires a user with 'read' permission (can be anonymous) 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param file_path: Path to the artifact within the repository. Can include special tokens: SNAPSHOT, [RELEASE], [INTEGRATION] for latest version resolution. (required)
        :type file_path: str
        :param skip_update_stats: Skip updating download statistics for this artifact
        :type skip_update_stats: bool
        :param trace: Simulates an artifact retrieval request and returns verbose output about the resolution process. Useful for debugging artifact retrieval issues.
        :type trace: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._retrieve_artifact_serialize(
            repo_key=repo_key,
            file_path=file_path,
            skip_update_stats=skip_update_stats,
            trace=trace,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def retrieve_artifact_with_http_info(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        file_path: Annotated[str, Field(min_length=1, strict=True, description="Path to the artifact within the repository. Can include special tokens: SNAPSHOT, [RELEASE], [INTEGRATION] for latest version resolution.")],
        skip_update_stats: Annotated[Optional[StrictBool], Field(description="Skip updating download statistics for this artifact")] = None,
        trace: Annotated[Optional[StrictBool], Field(description="Simulates an artifact retrieval request and returns verbose output about the resolution process. Useful for debugging artifact retrieval issues.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[bytes]:
        """Retrieve Artifact

        Returns an artifact from the specified destination.  You can also use properties in deployment and resolution as part of retrieving artifacts.  Special tokens for retrieving latest versions: - **Latest Maven Release/Integration**: Specify SNAPSHOT or [RELEASE] for the version in the requested path to get the latest Maven integration or release artifact. - **Latest Non-Maven Release/Integration**: Specify [INTEGRATION] and [RELEASE] for the version in the requested path (replacing [folderItegRev] and [fileItegRev], as defined by the repository's Repository Layouts) to get the latest integration version or latest release version artifact accordingly based on alphabetical sorting.  Notes: - Integration and release tokens cannot be mixed together. - Only local, cache and virtual repositories will be used for latest version resolution. - To change the retrieve latest behavior to retrieve the latest version based on the created date, add `artifactory.request.searchLatestReleaseByDateCreated=true` to `artifactory.system.properties` and restart Artifactory. - Both [folderItegRev] and [fileItegRev] have to be defined in the repository layout. - Latest version resolution requires Artifactory Pro.  Since: Latest Maven: 2.6.0; Latest non-Maven: 2.6.2 Security: Requires a user with 'read' permission (can be anonymous) 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param file_path: Path to the artifact within the repository. Can include special tokens: SNAPSHOT, [RELEASE], [INTEGRATION] for latest version resolution. (required)
        :type file_path: str
        :param skip_update_stats: Skip updating download statistics for this artifact
        :type skip_update_stats: bool
        :param trace: Simulates an artifact retrieval request and returns verbose output about the resolution process. Useful for debugging artifact retrieval issues.
        :type trace: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._retrieve_artifact_serialize(
            repo_key=repo_key,
            file_path=file_path,
            skip_update_stats=skip_update_stats,
            trace=trace,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def retrieve_artifact_without_preload_content(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        file_path: Annotated[str, Field(min_length=1, strict=True, description="Path to the artifact within the repository. Can include special tokens: SNAPSHOT, [RELEASE], [INTEGRATION] for latest version resolution.")],
        skip_update_stats: Annotated[Optional[StrictBool], Field(description="Skip updating download statistics for this artifact")] = None,
        trace: Annotated[Optional[StrictBool], Field(description="Simulates an artifact retrieval request and returns verbose output about the resolution process. Useful for debugging artifact retrieval issues.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieve Artifact

        Returns an artifact from the specified destination.  You can also use properties in deployment and resolution as part of retrieving artifacts.  Special tokens for retrieving latest versions: - **Latest Maven Release/Integration**: Specify SNAPSHOT or [RELEASE] for the version in the requested path to get the latest Maven integration or release artifact. - **Latest Non-Maven Release/Integration**: Specify [INTEGRATION] and [RELEASE] for the version in the requested path (replacing [folderItegRev] and [fileItegRev], as defined by the repository's Repository Layouts) to get the latest integration version or latest release version artifact accordingly based on alphabetical sorting.  Notes: - Integration and release tokens cannot be mixed together. - Only local, cache and virtual repositories will be used for latest version resolution. - To change the retrieve latest behavior to retrieve the latest version based on the created date, add `artifactory.request.searchLatestReleaseByDateCreated=true` to `artifactory.system.properties` and restart Artifactory. - Both [folderItegRev] and [fileItegRev] have to be defined in the repository layout. - Latest version resolution requires Artifactory Pro.  Since: Latest Maven: 2.6.0; Latest non-Maven: 2.6.2 Security: Requires a user with 'read' permission (can be anonymous) 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param file_path: Path to the artifact within the repository. Can include special tokens: SNAPSHOT, [RELEASE], [INTEGRATION] for latest version resolution. (required)
        :type file_path: str
        :param skip_update_stats: Skip updating download statistics for this artifact
        :type skip_update_stats: bool
        :param trace: Simulates an artifact retrieval request and returns verbose output about the resolution process. Useful for debugging artifact retrieval issues.
        :type trace: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._retrieve_artifact_serialize(
            repo_key=repo_key,
            file_path=file_path,
            skip_update_stats=skip_update_stats,
            trace=trace,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _retrieve_artifact_serialize(
        self,
        repo_key,
        file_path,
        skip_update_stats,
        trace,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if repo_key is not None:
            _path_params['repoKey'] = repo_key
        if file_path is not None:
            _path_params['filePath'] = file_path
        # process the query parameters
        if skip_update_stats is not None:
            
            _query_params.append(('skipUpdateStats', skip_update_stats))
            
        if trace is not None:
            
            _query_params.append(('trace', trace))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/octet-stream', 
                    'text/plain', 
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/artifactory/api/{repoKey}/{filePath}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def retrieve_build_artifacts_archive(
        self,
        build_artifacts_request: Annotated[BuildArtifactsRequest, Field(description="Build artifacts archive request")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> bytes:
        """Retrieve Build Artifacts Archive

        Returns an archive file (supports zip/tar/tar.gz/tgz) containing all the artifacts related to a specific build, you can optionally provide mappings to filter the results; the mappings support regexp capturing groups which enables you to dynamically construct the target path inside the result archive file.   Requires Artifactory Pro.  Since: 2.6.5  Security: Requires a privileged user (can be anonymous) 

        :param build_artifacts_request: Build artifacts archive request (required)
        :type build_artifacts_request: BuildArtifactsRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._retrieve_build_artifacts_archive_serialize(
            build_artifacts_request=build_artifacts_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def retrieve_build_artifacts_archive_with_http_info(
        self,
        build_artifacts_request: Annotated[BuildArtifactsRequest, Field(description="Build artifacts archive request")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[bytes]:
        """Retrieve Build Artifacts Archive

        Returns an archive file (supports zip/tar/tar.gz/tgz) containing all the artifacts related to a specific build, you can optionally provide mappings to filter the results; the mappings support regexp capturing groups which enables you to dynamically construct the target path inside the result archive file.   Requires Artifactory Pro.  Since: 2.6.5  Security: Requires a privileged user (can be anonymous) 

        :param build_artifacts_request: Build artifacts archive request (required)
        :type build_artifacts_request: BuildArtifactsRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._retrieve_build_artifacts_archive_serialize(
            build_artifacts_request=build_artifacts_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def retrieve_build_artifacts_archive_without_preload_content(
        self,
        build_artifacts_request: Annotated[BuildArtifactsRequest, Field(description="Build artifacts archive request")],
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieve Build Artifacts Archive

        Returns an archive file (supports zip/tar/tar.gz/tgz) containing all the artifacts related to a specific build, you can optionally provide mappings to filter the results; the mappings support regexp capturing groups which enables you to dynamically construct the target path inside the result archive file.   Requires Artifactory Pro.  Since: 2.6.5  Security: Requires a privileged user (can be anonymous) 

        :param build_artifacts_request: Build artifacts archive request (required)
        :type build_artifacts_request: BuildArtifactsRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._retrieve_build_artifacts_archive_serialize(
            build_artifacts_request=build_artifacts_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _retrieve_build_artifacts_archive_serialize(
        self,
        build_artifacts_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if build_artifacts_request is not None:
            _body_params = build_artifacts_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/zip', 
                    'application/x-tar', 
                    'application/x-gzip', 
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/artifactory/api/archive/buildArtifacts',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def retrieve_folder_or_repository_archive(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        path: Annotated[str, Field(min_length=1, strict=True, description="Path within the repository (use empty string for repository root)")],
        archive_type: Annotated[StrictStr, Field(description="Archive type")],
        include_checksum_files: Annotated[Optional[StrictBool], Field(description="Include checksum files in the archive")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> bytes:
        """Retrieve Folder or Repository Archive

        Returns an archive file (supports zip/tar/tar.gz/tgz) containing all the artifacts that reside under the specified path (folder or repository root). Requires Enable Folder Download to be set.   Requires Artifactory Pro.   Since: 4.1.0  Security: Requires a privileged user with read permissions on the path.  Downloading a folder or a repository's root is only supported for local (or cache) repositories. 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param path: Path within the repository (use empty string for repository root) (required)
        :type path: str
        :param archive_type: Archive type (required)
        :type archive_type: str
        :param include_checksum_files: Include checksum files in the archive
        :type include_checksum_files: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._retrieve_folder_or_repository_archive_serialize(
            repo_key=repo_key,
            path=path,
            archive_type=archive_type,
            include_checksum_files=include_checksum_files,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def retrieve_folder_or_repository_archive_with_http_info(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        path: Annotated[str, Field(min_length=1, strict=True, description="Path within the repository (use empty string for repository root)")],
        archive_type: Annotated[StrictStr, Field(description="Archive type")],
        include_checksum_files: Annotated[Optional[StrictBool], Field(description="Include checksum files in the archive")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[bytes]:
        """Retrieve Folder or Repository Archive

        Returns an archive file (supports zip/tar/tar.gz/tgz) containing all the artifacts that reside under the specified path (folder or repository root). Requires Enable Folder Download to be set.   Requires Artifactory Pro.   Since: 4.1.0  Security: Requires a privileged user with read permissions on the path.  Downloading a folder or a repository's root is only supported for local (or cache) repositories. 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param path: Path within the repository (use empty string for repository root) (required)
        :type path: str
        :param archive_type: Archive type (required)
        :type archive_type: str
        :param include_checksum_files: Include checksum files in the archive
        :type include_checksum_files: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._retrieve_folder_or_repository_archive_serialize(
            repo_key=repo_key,
            path=path,
            archive_type=archive_type,
            include_checksum_files=include_checksum_files,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def retrieve_folder_or_repository_archive_without_preload_content(
        self,
        repo_key: Annotated[str, Field(min_length=1, strict=True, description="Repository key")],
        path: Annotated[str, Field(min_length=1, strict=True, description="Path within the repository (use empty string for repository root)")],
        archive_type: Annotated[StrictStr, Field(description="Archive type")],
        include_checksum_files: Annotated[Optional[StrictBool], Field(description="Include checksum files in the archive")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Retrieve Folder or Repository Archive

        Returns an archive file (supports zip/tar/tar.gz/tgz) containing all the artifacts that reside under the specified path (folder or repository root). Requires Enable Folder Download to be set.   Requires Artifactory Pro.   Since: 4.1.0  Security: Requires a privileged user with read permissions on the path.  Downloading a folder or a repository's root is only supported for local (or cache) repositories. 

        :param repo_key: Repository key (required)
        :type repo_key: str
        :param path: Path within the repository (use empty string for repository root) (required)
        :type path: str
        :param archive_type: Archive type (required)
        :type archive_type: str
        :param include_checksum_files: Include checksum files in the archive
        :type include_checksum_files: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._retrieve_folder_or_repository_archive_serialize(
            repo_key=repo_key,
            path=path,
            archive_type=archive_type,
            include_checksum_files=include_checksum_files,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "bytes",
            '400': "ErrorResponse",
            '401': "ErrorResponse",
            '403': "ErrorResponse",
            '404': "ErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _retrieve_folder_or_repository_archive_serialize(
        self,
        repo_key,
        path,
        archive_type,
        include_checksum_files,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if repo_key is not None:
            _path_params['repoKey'] = repo_key
        if path is not None:
            _path_params['path'] = path
        # process the query parameters
        if archive_type is not None:
            
            _query_params.append(('archiveType', archive_type))
            
        if include_checksum_files is not None:
            
            _query_params.append(('includeChecksumFiles', include_checksum_files))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/zip', 
                    'application/x-tar', 
                    'application/x-gzip', 
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/artifactory/api/archive/download/{repoKey}/{path}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


