"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import Optional
from typing_extensions import Annotated
from jfrog_client.models.get_contextual_analysis_per_vulnerability_v2_contextual_analysis_v2_openapi200_response import GetContextualAnalysisPerVulnerabilityV2ContextualAnalysisV2Openapi200Response

from jfrog_client.api_client import ApiClient, RequestSerialized
from jfrog_client.api_response import ApiResponse
from jfrog_client.rest import RESTResponseType


class ContextualAnalysisV2Api:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def get_contextual_analysis_per_vulnerability_v2_contextual_analysis_v2_openapi(
        self,
        component_id: Annotated[StrictStr, Field(description="The component identifier to check applicability for (e.g. gav://group:artifact, npm://package).")],
        vulnerability_id: Annotated[StrictStr, Field(description="The vulnerability identifier (e.g. CVE-2021-44228).")],
        source_comp_id: Annotated[Optional[StrictStr], Field(description="Source component ID (the SBOM package that the vulnerability originates from). If given, only a result matching that component will be returned. If not given, returned results will contain data for any component in the artifact.")] = None,
        path: Annotated[Optional[StrictStr], Field(description="Artifact path used to identify the specific artifact. Without this, results may be aggregated from several artifacts. Only relevant for artifacts (not builds or release bundles).")] = None,
        user_issue_id: Annotated[Optional[StrictStr], Field(description="User issue identifier to narrow down the specific artifact.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> GetContextualAnalysisPerVulnerabilityV2ContextualAnalysisV2Openapi200Response:
        """Get Contextual Analysis per Vulnerability V2

        Returns contextual analysis results with evidence details and transitive dependency graph (v2 format). Requires Read permission.

        :param component_id: The component identifier to check applicability for (e.g. gav://group:artifact, npm://package). (required)
        :type component_id: str
        :param vulnerability_id: The vulnerability identifier (e.g. CVE-2021-44228). (required)
        :type vulnerability_id: str
        :param source_comp_id: Source component ID (the SBOM package that the vulnerability originates from). If given, only a result matching that component will be returned. If not given, returned results will contain data for any component in the artifact.
        :type source_comp_id: str
        :param path: Artifact path used to identify the specific artifact. Without this, results may be aggregated from several artifacts. Only relevant for artifacts (not builds or release bundles).
        :type path: str
        :param user_issue_id: User issue identifier to narrow down the specific artifact.
        :type user_issue_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_contextual_analysis_per_vulnerability_v2_contextual_analysis_v2_openapi_serialize(
            component_id=component_id,
            vulnerability_id=vulnerability_id,
            source_comp_id=source_comp_id,
            path=path,
            user_issue_id=user_issue_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetContextualAnalysisPerVulnerabilityV2ContextualAnalysisV2Openapi200Response",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_contextual_analysis_per_vulnerability_v2_contextual_analysis_v2_openapi_with_http_info(
        self,
        component_id: Annotated[StrictStr, Field(description="The component identifier to check applicability for (e.g. gav://group:artifact, npm://package).")],
        vulnerability_id: Annotated[StrictStr, Field(description="The vulnerability identifier (e.g. CVE-2021-44228).")],
        source_comp_id: Annotated[Optional[StrictStr], Field(description="Source component ID (the SBOM package that the vulnerability originates from). If given, only a result matching that component will be returned. If not given, returned results will contain data for any component in the artifact.")] = None,
        path: Annotated[Optional[StrictStr], Field(description="Artifact path used to identify the specific artifact. Without this, results may be aggregated from several artifacts. Only relevant for artifacts (not builds or release bundles).")] = None,
        user_issue_id: Annotated[Optional[StrictStr], Field(description="User issue identifier to narrow down the specific artifact.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[GetContextualAnalysisPerVulnerabilityV2ContextualAnalysisV2Openapi200Response]:
        """Get Contextual Analysis per Vulnerability V2

        Returns contextual analysis results with evidence details and transitive dependency graph (v2 format). Requires Read permission.

        :param component_id: The component identifier to check applicability for (e.g. gav://group:artifact, npm://package). (required)
        :type component_id: str
        :param vulnerability_id: The vulnerability identifier (e.g. CVE-2021-44228). (required)
        :type vulnerability_id: str
        :param source_comp_id: Source component ID (the SBOM package that the vulnerability originates from). If given, only a result matching that component will be returned. If not given, returned results will contain data for any component in the artifact.
        :type source_comp_id: str
        :param path: Artifact path used to identify the specific artifact. Without this, results may be aggregated from several artifacts. Only relevant for artifacts (not builds or release bundles).
        :type path: str
        :param user_issue_id: User issue identifier to narrow down the specific artifact.
        :type user_issue_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_contextual_analysis_per_vulnerability_v2_contextual_analysis_v2_openapi_serialize(
            component_id=component_id,
            vulnerability_id=vulnerability_id,
            source_comp_id=source_comp_id,
            path=path,
            user_issue_id=user_issue_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetContextualAnalysisPerVulnerabilityV2ContextualAnalysisV2Openapi200Response",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_contextual_analysis_per_vulnerability_v2_contextual_analysis_v2_openapi_without_preload_content(
        self,
        component_id: Annotated[StrictStr, Field(description="The component identifier to check applicability for (e.g. gav://group:artifact, npm://package).")],
        vulnerability_id: Annotated[StrictStr, Field(description="The vulnerability identifier (e.g. CVE-2021-44228).")],
        source_comp_id: Annotated[Optional[StrictStr], Field(description="Source component ID (the SBOM package that the vulnerability originates from). If given, only a result matching that component will be returned. If not given, returned results will contain data for any component in the artifact.")] = None,
        path: Annotated[Optional[StrictStr], Field(description="Artifact path used to identify the specific artifact. Without this, results may be aggregated from several artifacts. Only relevant for artifacts (not builds or release bundles).")] = None,
        user_issue_id: Annotated[Optional[StrictStr], Field(description="User issue identifier to narrow down the specific artifact.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Get Contextual Analysis per Vulnerability V2

        Returns contextual analysis results with evidence details and transitive dependency graph (v2 format). Requires Read permission.

        :param component_id: The component identifier to check applicability for (e.g. gav://group:artifact, npm://package). (required)
        :type component_id: str
        :param vulnerability_id: The vulnerability identifier (e.g. CVE-2021-44228). (required)
        :type vulnerability_id: str
        :param source_comp_id: Source component ID (the SBOM package that the vulnerability originates from). If given, only a result matching that component will be returned. If not given, returned results will contain data for any component in the artifact.
        :type source_comp_id: str
        :param path: Artifact path used to identify the specific artifact. Without this, results may be aggregated from several artifacts. Only relevant for artifacts (not builds or release bundles).
        :type path: str
        :param user_issue_id: User issue identifier to narrow down the specific artifact.
        :type user_issue_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_contextual_analysis_per_vulnerability_v2_contextual_analysis_v2_openapi_serialize(
            component_id=component_id,
            vulnerability_id=vulnerability_id,
            source_comp_id=source_comp_id,
            path=path,
            user_issue_id=user_issue_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "GetContextualAnalysisPerVulnerabilityV2ContextualAnalysisV2Openapi200Response",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_contextual_analysis_per_vulnerability_v2_contextual_analysis_v2_openapi_serialize(
        self,
        component_id,
        vulnerability_id,
        source_comp_id,
        path,
        user_issue_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        if component_id is not None:
            
            _query_params.append(('component_id', component_id))
            
        if vulnerability_id is not None:
            
            _query_params.append(('vulnerability_id', vulnerability_id))
            
        if source_comp_id is not None:
            
            _query_params.append(('source_comp_id', source_comp_id))
            
        if path is not None:
            
            _query_params.append(('path', path))
            
        if user_issue_id is not None:
            
            _query_params.append(('user_issue_id', user_issue_id))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/xray/api/v2/cve_applicability',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


