"""
    JFrog Platform API (Unofficial)

    **Unofficial** combined REST API spec for the JFrog Platform. This is not an official JFrog specification and may be incomplete or inaccurate.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import StrictStr
from jfrog_client.models.offline_token_request import OfflineTokenRequest

from jfrog_client.api_client import ApiClient, RequestSerialized
from jfrog_client.api_response import ApiResponse
from jfrog_client.rest import RESTResponseType


class EntitlementsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def post_offline_request_token(
        self,
        offline_token_request: OfflineTokenRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Post Offline Request Token to JFrog Entitlements Service

        Posts the offline request token from the air-gapped JPD to the JFrog Entitlements Service and returns the entitlements in JSON format.  You must run this API from a machine that has connectivity to the Internet.  The `offline_response_token` needed for applying entitlements is returned as a response header.  **Example 1 - Save the entitlements to a file:** ``` curl -v -L 'https://jes.jfrog.io/api/v1/offline_register' \\   -H 'Content-Type: application/json' \\   --data '{\"offline_request_token\": \"<offline_request_token>\"}' \\   > entitlements.json  ``` The `-v` flag prints the response headers (including `offline_response_token`) to stderr while saving the response body to `entitlements.json`.  **Example 2 - Extract only the `offline_response_token`:** ``` curl -s -L 'https://jes.jfrog.io/api/v1/offline_register' \\   -H 'Content-Type: application/json' \\   --data '{\"offline_request_token\": \"<offline_request_token>\"}' \\   -o /dev/null -D - | grep offline_response_token  ``` This discards the response body and prints only the `offline_response_token` header value to the screen.  You need **both** the `entitlements.json` file and the `offline_response_token` header value to complete the next step: applying entitlements to the air-gapped JPD using the JFConnect Apply Entitlements API.  **Warning:** If you save the response manually instead of directing the response body to an `entitlements.json` file, ensure that there are no spaces or any modifications. Any change in the response fails checksum validation when you apply entitlements. 

        :param offline_token_request: (required)
        :type offline_token_request: OfflineTokenRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_offline_request_token_serialize(
            offline_token_request=offline_token_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def post_offline_request_token_with_http_info(
        self,
        offline_token_request: OfflineTokenRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Post Offline Request Token to JFrog Entitlements Service

        Posts the offline request token from the air-gapped JPD to the JFrog Entitlements Service and returns the entitlements in JSON format.  You must run this API from a machine that has connectivity to the Internet.  The `offline_response_token` needed for applying entitlements is returned as a response header.  **Example 1 - Save the entitlements to a file:** ``` curl -v -L 'https://jes.jfrog.io/api/v1/offline_register' \\   -H 'Content-Type: application/json' \\   --data '{\"offline_request_token\": \"<offline_request_token>\"}' \\   > entitlements.json  ``` The `-v` flag prints the response headers (including `offline_response_token`) to stderr while saving the response body to `entitlements.json`.  **Example 2 - Extract only the `offline_response_token`:** ``` curl -s -L 'https://jes.jfrog.io/api/v1/offline_register' \\   -H 'Content-Type: application/json' \\   --data '{\"offline_request_token\": \"<offline_request_token>\"}' \\   -o /dev/null -D - | grep offline_response_token  ``` This discards the response body and prints only the `offline_response_token` header value to the screen.  You need **both** the `entitlements.json` file and the `offline_response_token` header value to complete the next step: applying entitlements to the air-gapped JPD using the JFConnect Apply Entitlements API.  **Warning:** If you save the response manually instead of directing the response body to an `entitlements.json` file, ensure that there are no spaces or any modifications. Any change in the response fails checksum validation when you apply entitlements. 

        :param offline_token_request: (required)
        :type offline_token_request: OfflineTokenRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_offline_request_token_serialize(
            offline_token_request=offline_token_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def post_offline_request_token_without_preload_content(
        self,
        offline_token_request: OfflineTokenRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Post Offline Request Token to JFrog Entitlements Service

        Posts the offline request token from the air-gapped JPD to the JFrog Entitlements Service and returns the entitlements in JSON format.  You must run this API from a machine that has connectivity to the Internet.  The `offline_response_token` needed for applying entitlements is returned as a response header.  **Example 1 - Save the entitlements to a file:** ``` curl -v -L 'https://jes.jfrog.io/api/v1/offline_register' \\   -H 'Content-Type: application/json' \\   --data '{\"offline_request_token\": \"<offline_request_token>\"}' \\   > entitlements.json  ``` The `-v` flag prints the response headers (including `offline_response_token`) to stderr while saving the response body to `entitlements.json`.  **Example 2 - Extract only the `offline_response_token`:** ``` curl -s -L 'https://jes.jfrog.io/api/v1/offline_register' \\   -H 'Content-Type: application/json' \\   --data '{\"offline_request_token\": \"<offline_request_token>\"}' \\   -o /dev/null -D - | grep offline_response_token  ``` This discards the response body and prints only the `offline_response_token` header value to the screen.  You need **both** the `entitlements.json` file and the `offline_response_token` header value to complete the next step: applying entitlements to the air-gapped JPD using the JFConnect Apply Entitlements API.  **Warning:** If you save the response manually instead of directing the response body to an `entitlements.json` file, ensure that there are no spaces or any modifications. Any change in the response fails checksum validation when you apply entitlements. 

        :param offline_token_request: (required)
        :type offline_token_request: OfflineTokenRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._post_offline_request_token_serialize(
            offline_token_request=offline_token_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': None,
            '500': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _post_offline_request_token_serialize(
        self,
        offline_token_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if offline_token_request is not None:
            _body_params = offline_token_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'text/plain'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/api/v1/offline_register',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


